### ISSUE TITLE
Display problems in the app

### ISSUE THREAD

**Issue by meni123** [silentbil/silent-bus#3] opened 2023-05-03 07:43 UTC
I have a problem with the display in the application (Android) as you can see in the picture,
In the browser it is excellent, but in the application there is no division between the columns,

2. Currently it shows the original arrival time and in addition a message about the real time deduction, is it possible to set it to show only the final arrival time, it is confusing to have to calculate the time deduction,
 
3. Is it possible to write the hours and minutes in Hebrew and not in English,

![צילום מסך 2023-05-03 103324](https://user-images.githubusercontent.com/49362774/235857977-7879bb40-1ffe-414e-936c-f1454bfbcad0.jpg)
Thank you very much for the wonderful plugin

**Comment by NatanCoralogix** [comment] 2023-05-03 09:50
Hi

1. is this a tablet? it looks like there was error in console, so the page is kind of broken
i will try to reproduce it
2. the time is not the  original time, it is already the real time arrival.
meaning: 
8 min = the bus will be here in 8 min
2 min delay = the original was to be here in 6 min, but he have 2 min delay.
bottom line is that the bus will be here in 8 min and by the way this bus has a total delay of 2 min

**Comment by meni123** [comment] 2023-05-03 10:11
1. The screenshot I attached is from a tablet, but I also checked on a smartphone and there was the same problem,
2. I got it, I thought it was the other way around,

**Comment by silentbil** [comment] 2023-05-06 08:00
@meni123 fixed on version v1.07
plz let me know if worked

**Comment by meni123** [comment] 2023-05-07 21:31
Great, now it's fine.
If you translate the minutes and hours into Hebrew, that would be wonderful,
Thank you

**Closed** 2023-05-11 10:32 UTC
